// =============================================================================
// VedaDB Server - Unified Configuration Generator
// =============================================================================
// Description:
//   A Go utility that generates OS-appropriate config.yaml files for VedaDB
//   Server. Used by all platform installers (Windows MSI, macOS PKG, Linux DEB)
//   to create consistent, sensible default configurations.
//
// Usage:
//   config-generator [flags]
//
// Flags:
//   --os string          Target OS: windows, darwin, linux (required)
//   --data-dir string    Data directory path (auto-detected per OS)
//   --log-dir string     Log directory path (auto-detected per OS)
//   --port int           Server listen port (default: 7480)
//   --bind string        Bind address (default: 0.0.0.0)
//   --admin-user string  Admin username (default: admin)
//   --admin-pass string  Admin password (auto-generated if not set)
//   --auth-enabled       Enable authentication (default: true)
//   --cache-size string  Cache size (default: 512MB)
//   --output string      Output file path (default: stdout)
//   --version            Show version information
//
// Examples:
//   # Generate default config for Linux
//   config-generator --os linux --output /etc/vedadb/config.yaml
//
//   # Generate with custom port and data directory
//   config-generator --os windows --port 9000 --data-dir D:\VedaDB\Data
//
//   # Generate for macOS with custom settings
//   config-generator --os darwin --port 8080 --bind 127.0.0.1
// =============================================================================

package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// InstallerVersion is set at build time
var InstallerVersion = "1.0.0"

// =============================================================================
// OS-Specific Defaults
// =============================================================================

type OSDefaults struct {
	DataDir       string
	LogDir        string
	ConfigPath    string
	ServiceName   string
	ServiceUser   string
	ServiceGroup  string
	BindAddress   string
	MaxOpenFiles  int
}

func getOSDefaults(os string) OSDefaults {
	switch os {
	case "windows":
		return OSDefaults{
			DataDir:      `C:\ProgramData\VedaDB\data`,
			LogDir:       `C:\ProgramData\VedaDB\logs`,
			ConfigPath:   `C:\ProgramData\VedaDB\config.yaml`,
			ServiceName:  "VedaDBServer",
			ServiceUser:  `NT AUTHORITY\NetworkService`,
			ServiceGroup: "",
			BindAddress:  "0.0.0.0",
			MaxOpenFiles: 65536,
		}
	case "darwin":
		return OSDefaults{
			DataDir:      "/usr/local/var/vedadb/data",
			LogDir:       "/usr/local/var/vedadb/logs",
			ConfigPath:   "/opt/vedadb/etc/config.yaml",
			ServiceName:  "io.vedadb.server",
			ServiceUser:  "_vedadb",
			ServiceGroup: "_vedadb",
			BindAddress:  "127.0.0.1", // macOS: localhost by default for security
			MaxOpenFiles: 65536,
		}
	case "linux":
		return OSDefaults{
			DataDir:      "/var/lib/vedadb/data",
			LogDir:       "/var/log/vedadb",
			ConfigPath:   "/etc/vedadb/config.yaml",
			ServiceName:  "vedadb",
			ServiceUser:  "vedadb",
			ServiceGroup: "vedadb",
			BindAddress:  "0.0.0.0",
			MaxOpenFiles: 65536,
		}
	default:
		// Return Linux defaults as fallback
		return getOSDefaults("linux")
	}
}

// =============================================================================
// Password Generation
// =============================================================================

// generatePassword creates a cryptographically secure random password.
func generatePassword(length int) string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
	b := make([]byte, length)
	rand.Read(b)
	for i := range b {
		b[i] = charset[int(b[i])%len(charset)]
	}
	return string(b)
}

// generatePasswordHash creates a bcrypt hash of the password.
// Note: This is a placeholder. In production, use golang.org/x/crypto/bcrypt
func generatePasswordHash(password string) string {
	// Placeholder hash format - real implementation would use bcrypt
	// For now, we store the hash prefix to indicate it's auto-generated
	return fmt.Sprintf("$2a$10$[AUTO_GENERATED_PASSWORD:%s]", password)
}

// =============================================================================
// Config Template
// =============================================================================

// configTemplate is the YAML configuration template.
const configTemplate = `# ============================================================================
# VedaDB Server Configuration
# Auto-generated by VedaDB Installer v{{.Version}}
# Generated at: {{.Timestamp}}
# Platform: {{.OS}} ({{.Arch}})
# ============================================================================

# Server configuration
server:
  # Port to listen on (default: 7480)
  port: {{.Port}}

  # Bind address (0.0.0.0 for all interfaces, 127.0.0.1 for localhost only)
  host: {{.BindAddress}}

  # Data directory for database files
  data_dir: "{{.DataDir}}"

  # Maximum concurrent client connections
  max_connections: 1000

  # Query timeout
  query_timeout: 30s

  # Maximum query memory per connection
  max_query_memory: 256MB

  # HTTP API endpoint
  http_api:
    enabled: true
    port: 7481
    bind: 127.0.0.1

  # Maximum open file descriptors
  max_open_files: {{.MaxOpenFiles}}

# Authentication
auth:
  enabled: {{.AuthEnabled}}
  method: password
  admin_user: {{.AdminUser}}
  # Admin password hash (bcrypt)
  # Auto-generated password: {{.AdminPassword}}
  admin_password_hash: "{{.AdminPasswordHash}}"

# Logging
logging:
  level: info
  file: "{{.LogDir}}/vedadb-server.log"
  max_size: 100MB
  max_files: 5
  format: json
  # Also log to stderr (useful for systemd/journald)
  stderr: false

# Storage engines - all enabled by default
engines:
  document:
    enabled: true
    max_collection_size: 0  # 0 = unlimited
  keyvalue:
    enabled: true
    max_key_size: 64KB
    max_value_size: 16MB
  graph:
    enabled: true
    max_vertices: 0  # 0 = unlimited
    max_edges: 0
  vector:
    enabled: true
    default_dimensions: 768
    max_dimensions: 1536
  timeseries:
    enabled: true
    retention: 30d
    max_series: 0  # 0 = unlimited

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 7d
  directory: "{{.DataDir}}/backups"
  compression: gzip

# Performance tuning
performance:
  # Number of worker threads (0 = auto = CPU cores)
  worker_threads: 0

  # Cache size for hot data
  cache_size: {{.CacheSize}}

  # Query result cache
  query_cache:
    enabled: true
    max_size: 64MB
    ttl: 5m

  # Write-ahead log
  wal:
    enabled: true
    sync_interval: 1s
    max_segment_size: 64MB

# Monitoring
monitoring:
  # Prometheus metrics endpoint
  metrics:
    enabled: true
    port: 7482
    bind: 127.0.0.1
    path: /metrics

  # Health check endpoint
  health:
    enabled: true
    port: 7483
    bind: 127.0.0.1
    path: /health

# Security
security:
  # TLS configuration (recommended for production)
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_second: 10000
    burst_size: 1000

  # Connection limits per IP
  connection_limit:
    enabled: true
    max_per_ip: 100

# Service configuration (OS-specific)
service:
  name: {{.ServiceName}}
  user: {{.ServiceUser}}
{{- if .ServiceGroup }}
  group: {{.ServiceGroup}}
{{- end }}
`

// =============================================================================
// Config Data
// =============================================================================

type ConfigData struct {
	Version           string
	Timestamp         string
	OS                string
	Arch              string
	Port              int
	BindAddress       string
	DataDir           string
	LogDir            string
	MaxOpenFiles      int
	AuthEnabled       bool
	AdminUser         string
	AdminPassword     string
	AdminPasswordHash string
	CacheSize         string
	ServiceName       string
	ServiceUser       string
	ServiceGroup      string
}

// =============================================================================
// Config Generation
// =============================================================================

func generateConfig(data *ConfigData) string {
	config := configTemplate

	// Simple template substitution (no external dependencies)
	replacements := map[string]string{
		"{{.Version}}":           data.Version,
		"{{.Timestamp}}":         data.Timestamp,
		"{{.OS}}":                data.OS,
		"{{.Arch}}":              data.Arch,
		"{{.Port}}":              fmt.Sprintf("%d", data.Port),
		"{{.BindAddress}}":       data.BindAddress,
		"{{.DataDir}}":           data.DataDir,
		"{{.LogDir}}":            data.LogDir,
		"{{.MaxOpenFiles}}":      fmt.Sprintf("%d", data.MaxOpenFiles),
		"{{.AuthEnabled}}":       fmt.Sprintf("%t", data.AuthEnabled),
		"{{.AdminUser}}":         data.AdminUser,
		"{{.AdminPassword}}":     data.AdminPassword,
		"{{.AdminPasswordHash}}": data.AdminPasswordHash,
		"{{.CacheSize}}":         data.CacheSize,
		"{{.ServiceName}}":       data.ServiceName,
		"{{.ServiceUser}}":       data.ServiceUser,
		"{{.ServiceGroup}}":      data.ServiceGroup,
	}

	result := config
	for key, value := range replacements {
		result = strings.ReplaceAll(result, key, value)
	}

	// Handle conditional service group
	if data.ServiceGroup == "" {
		result = strings.ReplaceAll(result, "  group: \n", "")
	}

	return result
}

// =============================================================================
// Main
// =============================================================================

func main() {
	var (
		osFlag        = flag.String("os", "", "Target OS: windows, darwin, linux (detected automatically if not set)")
		dataDirFlag   = flag.String("data-dir", "", "Data directory path (auto-detected per OS if not set)")
		logDirFlag    = flag.String("log-dir", "", "Log directory path (auto-detected per OS if not set)")
		portFlag      = flag.Int("port", 7480, "Server listen port")
		bindFlag      = flag.String("bind", "", "Bind address (auto-detected per OS if not set)")
		adminUserFlag = flag.String("admin-user", "admin", "Admin username")
		adminPassFlag = flag.String("admin-pass", "", "Admin password (auto-generated if not set)")
		authEnabled   = flag.Bool("auth-enabled", true, "Enable authentication")
		cacheSizeFlag = flag.String("cache-size", "512MB", "Cache size")
		outputFlag    = flag.String("output", "", "Output file path (stdout if not set)")
		showVersion   = flag.Bool("version", false, "Show version and exit")
	)

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "VedaDB Configuration Generator v%s\n\n", InstallerVersion)
		fmt.Fprintf(os.Stderr, "Usage: %s [options]\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Generates OS-appropriate config.yaml for VedaDB Server.\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExamples:\n")
		fmt.Fprintf(os.Stderr, "  %s --os linux --output /etc/vedadb/config.yaml\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --os windows --port 9000 --data-dir D:\\VedaDB\\Data\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  %s --os darwin --bind 127.0.0.1\n", os.Args[0])
	}

	flag.Parse()

	// Show version
	if *showVersion {
		fmt.Printf("VedaDB Config Generator v%s\n", InstallerVersion)
		fmt.Printf("Built for: %s/%s\n", runtime.GOOS, runtime.GOARCH)
		os.Exit(0)
	}

	// Detect OS
	targetOS := *osFlag
	if targetOS == "" {
		targetOS = runtime.GOOS
		if targetOS == "darwin" {
			targetOS = "darwin"
		}
	}

	// Normalize OS name
	switch targetOS {
	case "windows", "win32", "win64":
		targetOS = "windows"
	case "darwin", "macos", "osx":
		targetOS = "darwin"
	case "linux":
		targetOS = "linux"
	default:
		fmt.Fprintf(os.Stderr, "Error: Unsupported OS '%s'. Use: windows, darwin, linux\n", targetOS)
		os.Exit(1)
	}

	// Get OS defaults
	defaults := getOSDefaults(targetOS)

	// Determine paths
	dataDir := *dataDirFlag
	if dataDir == "" {
		dataDir = defaults.DataDir
	}

	logDir := *logDirFlag
	if logDir == "" {
		logDir = defaults.LogDir
	}

	bindAddr := *bindFlag
	if bindAddr == "" {
		bindAddr = defaults.BindAddress
	}

	// Generate password
	adminPassword := *adminPassFlag
	if adminPassword == "" {
		adminPassword = generatePassword(16)
	}
	adminPasswordHash := generatePasswordHash(adminPassword)

	// Build config data
	configData := &ConfigData{
		Version:           InstallerVersion,
		Timestamp:         time.Now().UTC().Format(time.RFC3339),
		OS:                targetOS,
		Arch:              runtime.GOARCH,
		Port:              *portFlag,
		BindAddress:       bindAddr,
		DataDir:           filepath.ToSlash(dataDir),
		LogDir:            filepath.ToSlash(logDir),
		MaxOpenFiles:      defaults.MaxOpenFiles,
		AuthEnabled:       *authEnabled,
		AdminUser:         *adminUserFlag,
		AdminPassword:     adminPassword,
		AdminPasswordHash: adminPasswordHash,
		CacheSize:         *cacheSizeFlag,
		ServiceName:       defaults.ServiceName,
		ServiceUser:       defaults.ServiceUser,
		ServiceGroup:      defaults.ServiceGroup,
	}

	// Generate configuration
	config := generateConfig(configData)

	// Write output
	outputPath := *outputFlag
	if outputPath == "" {
		// Print to stdout
		fmt.Println(config)
	} else {
		// Create parent directory if needed
		dir := filepath.Dir(outputPath)
		if err := os.MkdirAll(dir, 0750); err != nil {
			fmt.Fprintf(os.Stderr, "Error: Failed to create directory %s: %v\n", dir, err)
			os.Exit(1)
		}

		if err := os.WriteFile(outputPath, []byte(config), 0640); err != nil {
			fmt.Fprintf(os.Stderr, "Error: Failed to write config: %v\n", err)
			os.Exit(1)
		}

		fmt.Printf("Configuration written to: %s\n", outputPath)
		fmt.Printf("Admin password (auto-generated): %s\n", adminPassword)
		fmt.Printf("Remember to change this password after first login!\n")
	}
}
